"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""


fibo_sum = 0
fibo_nums = [0, 1]

while fibo_nums[-1] < 4000000:

	for i in fibo_nums:

		fibo = fibo_nums[i-1]+fibo_nums[i-2]
		fibo_nums.append(fibo)
		break

	fibo_sum += fibo
fibo_nums = set(fibo_nums)

even_sum=0

for num in fibo_nums:
	if num%2 == 0:
		even_sum += num

print(even_sum)